frontend/app/build.gradle
frontend/app/src/main/java/com/example/wwmeet_android/AppointmentBeforeAdapter.java
frontend/app/src/main/java/com/example/wwmeet_android/MainActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/domain/Appointment.java
frontend/app/src/main/res/layout/activity_main.xml
frontend/app/src/main/res/layout/item_appointment_list.xml

홈 뷰, 홈 기능 완성

---

backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/controller/AppointmentController.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/repository/AppointmentRepository.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/service/AppointmentService.java

Appointment Controller, Service, Repository 생성 완료

Appointment(약속) 레이어 생성

---

backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/domain/Appointment.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/domain/Vote.java
backend/WWMeet_backend/src/main/resources/application.properties

Entity, application.properties 추가 및 수정

Database 기능 추가

---

backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/domain/Appointment.java

Appointment 클래스 명확한 필드명으로 리펙토링

#3 - 도메인 리펙토링

---

backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/dto/ParticipantAndAppointmentDto.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/service/ParticipantService.java
backend/WWMeet_backend/src/test/java/com/example/wwmeet_backend/controller/AppointmentControllerTest.java
backend/WWMeet_backend/src/test/java/com/example/wwmeet_backend/controller/ParticipantControllerTest.java
backend/WWMeet_backend/src/test/java/com/example/wwmeet_backend/repository/ParticipantRepositoryTest.java
backend/WWMeet_backend/src/test/java/com/example/wwmeet_backend/service/ParticipantServiceTest.java

참가자를 추가 하는 기능의 Controller, Service, Repository 테스트 코드를 작성함

add participant 테스트 코드

---

backend/WWMeet_backend/src/main/generated/com/example/wwmeet_backend/mapper/AppointmentMapperImpl.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/controller/AppointmentController.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/controller/ParticipantController.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/dto/ParticipantResponse.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/dto/SaveAppointmentResponseDto.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/mapper/AppointmentMapper.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/repository/AppointmentRepository.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/service/AppointmentService.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/service/ParticipantService.java
backend/WWMeet_backend/src/test/java/com/example/wwmeet_backend/controller/ParticipantControllerTest.java
backend/WWMeet_backend/src/test/java/com/example/wwmeet_backend/repository/AppointmentRepositoryTest.java
backend/WWMeet_backend/src/test/java/com/example/wwmeet_backend/service/AppointmentServiceTest.java

add participant 참가자 추가 기능 운영 코드

---

backend/WWMeet_backend/build.gradle
backend/WWMeet_backend/src/main/resources/application-local.properties
backend/WWMeet_backend/src/main/resources/application-prod.properties

여러 환경에서 개발을 하기 위해 profile을 설정함
로컬 환경을 위한 application-local.properties, 운영 환경을 위한 application-prod.properties를 추가하고
gradle 실행을 위해 build.gradle 파일을 수정함

feat: profile 설정을 위한 properties 생성 및 gradle 수정

---

backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/appointment/controller/AppointmentController.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/appointment/domain/Appointment.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/appointmentDate/domain/AppointmentDate.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/participant/domain/Participant.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/participant/service/ParticipantService.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/possibleschedule/domain/PossibleSchedule.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/vote/domain/Vote.java
backend/WWMeet_backend/src/test/java/com/example/wwmeet_backend/controller/VoteControllerTest.java

전체적으로 가독성에 좋게 리팩토링 후 javax -> jakarta로 변경
전체적인 코드 리팩토링
변수명, 메서드명 변경
javax -> jakarta 의존성으로 변경

Refactor: 코드 전체 리팩토링 및 오류 해결

---

frontend/app/src/main/res/drawable/background_box.xml

background로 사용 할 박스 레이아웃을 만든다
backgroud_box.xml 파일을 생성함

Feat: 박스 레이아웃 추가

---

frontend/app/src/main/AndroidManifest.xml
frontend/app/src/main/java/com/example/wwmeet_android/AppointmentCreateActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/SetVoteDeadlineActivity.java
frontend/app/src/main/res/layout/activity_set_vote_deadline.xml
frontend/app/src/main/res/values/themes.xml

set-vote-deadline-page에 DatePicker, TimePicker, button 생성
화면 구성

Feat: activity_set_vote_deadline 레이아웃 작성

---

frontend/app/src/main/AndroidManifest.xml
frontend/app/src/main/java/com/example/wwmeet_android/EntranceActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/MainActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/SetVoteDeadlineActivity.java
frontend/app/src/main/res/layout/activity_appointment_create.xml
frontend/app/src/main/res/layout/activity_entrance.xml
frontend/app/src/main/res/layout/activity_set_vote_deadline.xml

entrance-page 화면 구성
레이아웃 생성
main-page와 entrance-page 연결

Feat: activity_entrance 레이아웃 작성

---

frontend/app/src/main/AndroidManifest.xml
frontend/app/src/main/java/com/example/wwmeet_android/AppointmentCreateActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/AppointmentInfoAfterActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/AppointmentInfoBeforeActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/CreateAppointmentActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/EntranceAppointmentActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/InviteAppointmentActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/MainActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/SetVoteDeadlineActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/VoteScheduleActivity.java
frontend/app/src/main/res/layout/activity_invite_apm.xml

뒤로가기 클릭시 어플이 종료되는 버그 수정
모든 액티비티 파일의 finish() 를 제거

Fix: 뒤로가기시 종료되는 버그 수정

---

frontend/app/src/main/java/com/example/wwmeet_android/AppointmentCreateActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/MainActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/SetVoteDeadlineActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/VoteScheduleActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/dto/PossibleScheduleRequest.java
frontend/app/src/main/java/com/example/wwmeet_android/dto/SaveAppointmentRequest.java
frontend/app/src/main/java/com/example/wwmeet_android/dto/VoteScheduleRequest.java
frontend/app/src/main/java/com/example/wwmeet_android/network/RetrofitService.java
frontend/app/src/main/res/layout/activity_vote_schedule.xml

약속 투표 기능 및 투표 후 조회 기능 완료
약속에 투표하는 기능 추가, 투표 후 조회 기능 완료

feat: 약속 조회 및 투표 기능 완료

---

backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/appointment/controller/AppointmentController.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/appointment/dto/response/FindAppointmentListResponse.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/appointment/dto/response/FindAppointmentVoteStatus.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/appointment/service/AppointmentService.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/possibleschedule/dto/SavePossibleScheduleRequest.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/vote/controller/VoteController.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/vote/service/VoteService.java
backend/WWMeet_backend/src/main/resources/application-local.properties
backend/WWMeet_backend/src/main/resources/application.properties
backend/WWMeet_backend/src/test/java/com/example/wwmeet_backend/service/AppointmentServiceTest.java

백엔드 투표 기능 완료 및 조회 기능 수정
투표 기능 완료
기능 수정

feat: 투표 기능 완료 및 조회 기능 수정

---

backend/WWMeet_backend/Dockerfile

배포를 위해 도커 빌드용 실행 파일을 추가함
.jar 를 실행하도록 만듬

feat: docker 파일 추가

---

backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/address/domain/Address.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/address/repository/AddressRepository.java

약속 참가자의 주소를 저장하기 위해  엔티티를 추가함
address 도메인 추가

feat: 주소 도메인 추가

---

frontend/app/src/main/java/com/example/wwmeet_android/appointment/info/AppointmentInfoAfterActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/appointment/info/AppointmentInfoBeforeActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/appointment/info/PlaceResultActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/appointment/info/UserLocationListAdapter.java
frontend/app/src/main/java/com/example/wwmeet_android/domain/UserLocation.java
frontend/app/src/main/res/layout/activity_appointment_info_after.xml
frontend/app/src/main/res/layout/activity_appointment_info_before.xml
frontend/app/src/main/res/layout/activity_place_result.xml
frontend/app/src/main/res/layout/item_user_location_list.xml

안드로이드 place_result 페이지 레이아웃 구성
place_result 자바 파일 생성
UserLocation,UserLocationListAdapter 자바 파일 생성- recyclerview 생성

Feat: place_result 페이지 레이아웃

---

frontend/app/build.gradle
frontend/app/src/main/AndroidManifest.xml
frontend/app/src/main/java/com/example/wwmeet_android/appointment/create/LocationSettingActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/util/KaKaoAPI.java
frontend/app/src/main/res/layout/activity_location_setting.xml
frontend/settings.gradle

네이버 맵의 자신의 위치 추가 마커 찍기 까지 완료
네이버 맵 기본 완성

feat: 네이버 맵 기능 추가

---

AI/Flask Emotion Analysis.py

Flask AI Code

---

frontend/app/src/main/java/com/example/wwmeet_android/network/AIRetrofitProvider.java
frontend/app/src/main/java/com/example/wwmeet_android/network/RetrofitAIService.java

AI 서버와 연결을 위한 안드로이드 레트로핏 설정
AIRetrofit 파일 생성

feat: 안드로이드 AI 연결을 위한 레트로핏 설정

---

frontend/app/src/main/AndroidManifest.xml
frontend/app/src/main/java/com/example/wwmeet_android/appointment/info/AppointmentInfoAfterActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/appointment/info/restaurant/AIFoodActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/appointment/info/restaurant/AIFoodResultActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/appointment/info/restaurant/FoodSearchActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/appointment/info/restaurant/RestaurantListAdapter.java
frontend/app/src/main/res/layout/activity_ai_food.xml
frontend/app/src/main/res/layout/activity_ai_food_result.xml
frontend/app/src/main/res/layout/activity_food_search.xml

맛집, 인공지능 안드로이드 레이아웃 구성
인공지능 관련 액티비티 추가

feat: 안드로이드 화면 구성

---

AI/Flask Server.py

Flask AI Server

---

frontend/app/src/main/AndroidManifest.xml
frontend/app/src/main/java/com/example/wwmeet_android/MainActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/appointment/info/restaurant/AIFoodActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/appointment/info/restaurant/AIFoodResultActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/dto/FindAnalysisResponse.java
frontend/app/src/main/java/com/example/wwmeet_android/network/AIRetrofitProvider.java
frontend/app/src/main/java/com/example/wwmeet_android/network/RetrofitAIService.java
frontend/app/src/main/java/com/example/wwmeet_android/util/KaKaoAPI.java
frontend/app/src/main/res/layout/activity_ai_food.xml
frontend/app/src/main/res/layout/activity_ai_food_result.xml

flask와 안드로이드 연결
결과 정보 띄우기
이미지 map

Feat: flask 연결 코드 작성

---

frontend/app/src/main/AndroidManifest.xml
frontend/app/src/main/java/com/example/wwmeet_android/SignUpActivity.java
frontend/app/src/main/res/layout/activity_sign_up.xml

회원가입을 할 수 있는 화면 생성
signUp activity 생성

feat: 회원가입 화면 생성

---

frontend/app/src/main/java/com/example/wwmeet_android/MainActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/StartActivity.java
frontend/app/src/main/res/layout/activity_main.xml

안드로이드 로그인이 유지되도록 설정
로그아웃 버튼, 기능 추가
토큰 존재 여부 체크 후 화면 켜지게 변경
로그아웃 기능 추가

로그인 유지, 로그아웃

---

backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/domain/appointment/controller/AppointmentController.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/domain/appointment/service/AppointmentService.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/domain/participant/repository/ParticipantRepository.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/domain/participant/service/ParticipantService.java
frontend/app/src/main/java/com/example/wwmeet_android/appointment/entrance/EntranceAppointmentActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/network/RetrofitService.java

member 도메인 추가로 생긴 오류 약속 입장 로직 수정
약속 입장 시 member를 추가하도록 수정
중복 입장인지 체크하는 로직을 삭제하고 입장 시 체크하게 변경

약속 입장 로직 수정

---

backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/domain/appointment/controller/AppointmentController.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/domain/appointment/service/AppointmentService.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/domain/participant/repository/ParticipantRepository.java

약속 전체 조회 오류 수정
participant를 통해 약속을 찾도록 변경

약속 전체 조회 오류 수정

---

backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/domain/appointment/service/AppointmentService.java
frontend/app/src/main/java/com/example/wwmeet_android/MainActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/appointment/info/AppointmentInfoAfterActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/appointment/info/AppointmentListAdapter.java

투표가 끝난 약속을 조회하지 못하는 오류를 수정
약속 일정을 하나만 조회하는 문제가 발생
전체 조회 후 투표율 높은 시간을 반환하도록 로직 변경

투표 끝난 약속 조회 오류 수정

---

backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/domain/appointment/controller/AppointmentController.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/domain/member/controller/MemberController.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/domain/participant/controller/ParticipantController.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/domain/place/controller/PlaceController.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/domain/restaurant/controller/RestaurantImageController.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/domain/vote/controller/VoteController.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/global/response/ResponseAPI.java

base response를 적용해 응답 예외를 세분화
ResponseEntity에 dto를 반환하던 것에서 base response를 덧씌워 반환하도록 변경

base response 적용

---

backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/domain/member/controller/MemberController.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/domain/member/dto/response/SignInResponse.java
backend/WWMeet_backend/src/main/java/com/example/wwmeet_backend/global/response/ResponseAPI.java
frontend/app/src/main/java/com/example/wwmeet_android/MainActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/appointment/create/SetVoteDeadlineActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/appointment/entrance/EntranceAppointmentActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/appointment/info/AppointmentInfoAfterActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/appointment/info/AppointmentInfoBeforeActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/appointment/info/PlaceResultActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/appointment/info/restaurant/FoodSearchActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/appointment/vote/VoteScheduleActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/member/SignInActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/member/SignUpActivity.java
frontend/app/src/main/java/com/example/wwmeet_android/member/dto/SignInResponse.java
frontend/app/src/main/java/com/example/wwmeet_android/network/ResponseAPI.java
frontend/app/src/main/java/com/example/wwmeet_android/network/RetrofitService.java

base response 에 맞춰 안드로이드의 통신 응답 값 변경
전체 Api의 응답 값을 base response로 통일

API response 통일/수정
